services:
  app:
    build: .
    container_name: Kremowka
    command: python3.9 main.py
    volumes:
      - .:/discord_bot
    environment:
      - APIKEYTFT=RGAPI-f6cda379-2634-455d-804f-de7c412cd1e8
      - MONGOURL=mongodb+srv://DzonyMongony:DzonyBravo12345@creamdatabase.pju7t.mongodb.net/Discord_Bot_Database
      - PYTHONUNBUFFERED=1